-- INSERTS FOR shop
CREATE TABLE shop (
id INTEGER PRIMARY KEY,
name VARCHAR(255) UNIQUE,
balance FLOAT NOT NULL);

INSERT INTO shop (id, name, balance) VALUES (1, 'Магнит', 53960);
INSERT INTO shop (id, name, balance) VALUES (2, 'Пятерочка', 375447);
INSERT INTO shop (id, name, balance) VALUES (3, 'Перекресток', 85583);
INSERT INTO shop (id, name, balance) VALUES (4, 'Лента', 388125);
INSERT INTO shop (id, name, balance) VALUES (5, 'Ашан', 429730);
INSERT INTO shop (id, name, balance) VALUES (6, 'METRO', 89919);
INSERT INTO shop (id, name, balance) VALUES (7, 'Дикси', 253218);
INSERT INTO shop (id, name, balance) VALUES (8, 'ВкусВилл', 271492);
INSERT INTO shop (id, name, balance) VALUES (9, 'Ozon Fresh', 107440);
INSERT INTO shop (id, name, balance) VALUES (10, 'Яндекс Лавка', 32595);

-- INSERTS FOR product
CREATE TABLE product (
id INTEGER PRIMARY KEY,
name VARCHAR(255) UNIQUE,
price FLOAT NOT NULL);

INSERT INTO product (id, name, price) VALUES (1, 'Хлеб белый', 2317);
INSERT INTO product (id, name, price) VALUES (2, 'Хлеб черный', 4590);
INSERT INTO product (id, name, price) VALUES (3, 'Молоко 3.2%', 2440);
INSERT INTO product (id, name, price) VALUES (4, 'Кефир 2.5%', 3754);
INSERT INTO product (id, name, price) VALUES (5, 'Сметана 15%', 4288);
INSERT INTO product (id, name, price) VALUES (6, 'Творог 5%', 2651);
INSERT INTO product (id, name, price) VALUES (7, 'Сыр Российский', 4867);
INSERT INTO product (id, name, price) VALUES (8, 'Йогурт клубничный', 3664);
INSERT INTO product (id, name, price) VALUES (9, 'Масло сливочное', 4952);
INSERT INTO product (id, name, price) VALUES (10, 'Яйца куриные 10 шт', 2338);
INSERT INTO product (id, name, price) VALUES (11, 'Курица охлажденная', 3323);
INSERT INTO product (id, name, price) VALUES (12, 'Говядина мякоть', 654);
INSERT INTO product (id, name, price) VALUES (13, 'Свинина вырезка', 2482);
INSERT INTO product (id, name, price) VALUES (14, 'Фарш говяжий', 3546);
INSERT INTO product (id, name, price) VALUES (15, 'Колбаса докторская', 735);
INSERT INTO product (id, name, price) VALUES (16, 'Сосиски молочные', 574);
INSERT INTO product (id, name, price) VALUES (17, 'Картофель', 455);
INSERT INTO product (id, name, price) VALUES (18, 'Лук репчатый', 2708);
INSERT INTO product (id, name, price) VALUES (19, 'Морковь', 177);
INSERT INTO product (id, name, price) VALUES (20, 'Огурцы свежие', 515);
INSERT INTO product (id, name, price) VALUES (21, 'Помидоры', 2345);
INSERT INTO product (id, name, price) VALUES (22, 'Яблоки Голден', 4630);
INSERT INTO product (id, name, price) VALUES (23, 'Бананы', 386);
INSERT INTO product (id, name, price) VALUES (24, 'Апельсины', 3899);
INSERT INTO product (id, name, price) VALUES (25, 'Лимоны', 1261);
INSERT INTO product (id, name, price) VALUES (26, 'Сахар 1 кг', 649);
INSERT INTO product (id, name, price) VALUES (27, 'Соль поваренная', 3052);
INSERT INTO product (id, name, price) VALUES (28, 'Мука пшеничная', 4612);
INSERT INTO product (id, name, price) VALUES (29, 'Рис круглый', 4983);
INSERT INTO product (id, name, price) VALUES (30, 'Гречневая крупа', 2564);
INSERT INTO product (id, name, price) VALUES (31, 'Овсяные хлопья', 1609);
INSERT INTO product (id, name, price) VALUES (32, 'Макароны', 911);
INSERT INTO product (id, name, price) VALUES (33, 'Подсолнечное масло', 3562);
INSERT INTO product (id, name, price) VALUES (34, 'Майонез', 2434);
INSERT INTO product (id, name, price) VALUES (35, 'Кетчуп', 54);
INSERT INTO product (id, name, price) VALUES (36, 'Чай черный', 3922);
INSERT INTO product (id, name, price) VALUES (37, 'Кофе молотый', 239);
INSERT INTO product (id, name, price) VALUES (38, 'Печенье овсяное', 1155);
INSERT INTO product (id, name, price) VALUES (39, 'Шоколад молочный', 4909);
INSERT INTO product (id, name, price) VALUES (40, 'Конфеты шоколадные', 4213);
INSERT INTO product (id, name, price) VALUES (41, 'Сок яблочный', 2186);
INSERT INTO product (id, name, price) VALUES (42, 'Вода минеральная', 3965);
INSERT INTO product (id, name, price) VALUES (43, 'Газированный напиток', 4488);
INSERT INTO product (id, name, price) VALUES (44, 'Пиво светлое', 3688);
INSERT INTO product (id, name, price) VALUES (45, 'Вино красное', 2257);
INSERT INTO product (id, name, price) VALUES (46, 'Туалетная бумага', 2238);
INSERT INTO product (id, name, price) VALUES (47, 'Мыло туалетное', 4205);
INSERT INTO product (id, name, price) VALUES (48, 'Шампунь', 2981);
INSERT INTO product (id, name, price) VALUES (49, 'Зубная паста', 3858);
INSERT INTO product (id, name, price) VALUES (50, 'Стиральный порошок', 1075);

-- INSERTS FOR warehouse (NO UPSERT, compatible with Jade)
CREATE TABLE warehouse (
shop_id INTEGER REFERENCES shop (id),
product_id INTEGER REFERENCES product (id),
quantity INTEGER NOT NULL,
PRIMARY KEY (shop_id, product_id));

INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Хлеб белый'), 43);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ozon Fresh'), (SELECT id FROM product WHERE name = 'Лук репчатый'), 88);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Молоко 3.2%'), 109);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Яндекс Лавка'), (SELECT id FROM product WHERE name = 'Шампунь'), 97);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Кетчуп'), 34);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Шампунь'), 159);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Гречневая крупа'), 104);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'ВкусВилл'), (SELECT id FROM product WHERE name = 'Яйца куриные 10 шт'), 30);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Дикси'), (SELECT id FROM product WHERE name = 'Йогурт клубничный'), 124);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Яндекс Лавка'), (SELECT id FROM product WHERE name = 'Сахар 1 кг'), 64);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Молоко 3.2%'), 138);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Лента'), (SELECT id FROM product WHERE name = 'Сосиски молочные'), 28);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ozon Fresh'), (SELECT id FROM product WHERE name = 'Лук репчатый'), 30);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Яндекс Лавка'), (SELECT id FROM product WHERE name = 'Кофе молотый'), 111);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Лента'), (SELECT id FROM product WHERE name = 'Огурцы свежие'), 46);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Лук репчатый'), 3);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Хлеб белый'), 49);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Сахар 1 кг'), 93);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Лента'), (SELECT id FROM product WHERE name = 'Огурцы свежие'), 71);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'ВкусВилл'), (SELECT id FROM product WHERE name = 'Кофе молотый'), 136);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Дикси'), (SELECT id FROM product WHERE name = 'Фарш говяжий'), 88);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Огурцы свежие'), 2);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Мука пшеничная'), 140);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'ВкусВилл'), (SELECT id FROM product WHERE name = 'Шампунь'), 170);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Яндекс Лавка'), (SELECT id FROM product WHERE name = 'Помидоры'), 194);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Йогурт клубничный'), 72);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Помидоры'), 12);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Дикси'), (SELECT id FROM product WHERE name = 'Кофе молотый'), 170);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Говядина мякоть'), 88);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Сыр Российский'), 113);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Туалетная бумага'), 146);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'ВкусВилл'), (SELECT id FROM product WHERE name = 'Сок яблочный'), 158);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'ВкусВилл'), (SELECT id FROM product WHERE name = 'Лимоны'), 18);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ашан'), (SELECT id FROM product WHERE name = 'Творог 5%'), 72);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Картофель'), 149);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ашан'), (SELECT id FROM product WHERE name = 'Подсолнечное масло'), 41);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Картофель'), 102);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Рис круглый'), 7);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Помидоры'), 26);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Сосиски молочные'), 197);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ашан'), (SELECT id FROM product WHERE name = 'Мука пшеничная'), 150);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Дикси'), (SELECT id FROM product WHERE name = 'Говядина мякоть'), 72);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Вода минеральная'), 136);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Молоко 3.2%'), 174);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ozon Fresh'), (SELECT id FROM product WHERE name = 'Макароны'), 144);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Дикси'), (SELECT id FROM product WHERE name = 'Соль поваренная'), 194);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ozon Fresh'), (SELECT id FROM product WHERE name = 'Конфеты шоколадные'), 152);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Сметана 15%'), 105);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Сметана 15%'), 26);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Сосиски молочные'), 163);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Масло сливочное'), 137);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Сахар 1 кг'), 13);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Яндекс Лавка'), (SELECT id FROM product WHERE name = 'Яблоки Голден'), 40);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ozon Fresh'), (SELECT id FROM product WHERE name = 'Гречневая крупа'), 195);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Конфеты шоколадные'), 147);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Дикси'), (SELECT id FROM product WHERE name = 'Шоколад молочный'), 140);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Дикси'), (SELECT id FROM product WHERE name = 'Яблоки Голден'), 88);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Хлеб черный'), 48);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Овсяные хлопья'), 139);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Творог 5%'), 108);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Лента'), (SELECT id FROM product WHERE name = 'Курица охлажденная'), 180);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Дикси'), (SELECT id FROM product WHERE name = 'Сок яблочный'), 60);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ашан'), (SELECT id FROM product WHERE name = 'Зубная паста'), 147);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Лук репчатый'), 101);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Майонез'), 94);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ozon Fresh'), (SELECT id FROM product WHERE name = 'Кетчуп'), 107);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ozon Fresh'), (SELECT id FROM product WHERE name = 'Масло сливочное'), 200);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Зубная паста'), 182);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Хлеб белый'), 27);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Мука пшеничная'), 132);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Курица охлажденная'), 17);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Мука пшеничная'), 11);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ашан'), (SELECT id FROM product WHERE name = 'Подсолнечное масло'), 44);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Говядина мякоть'), 105);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ашан'), (SELECT id FROM product WHERE name = 'Апельсины'), 168);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'ВкусВилл'), (SELECT id FROM product WHERE name = 'Молоко 3.2%'), 56);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ашан'), (SELECT id FROM product WHERE name = 'Газированный напиток'), 176);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Сок яблочный'), 154);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Яндекс Лавка'), (SELECT id FROM product WHERE name = 'Пиво светлое'), 3);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Лента'), (SELECT id FROM product WHERE name = 'Рис круглый'), 60);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Майонез'), 95);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Майонез'), 127);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Гречневая крупа'), 136);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Подсолнечное масло'), 194);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ашан'), (SELECT id FROM product WHERE name = 'Яйца куриные 10 шт'), 126);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Яйца куриные 10 шт'), 35);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ozon Fresh'), (SELECT id FROM product WHERE name = 'Сметана 15%'), 101);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Пиво светлое'), 171);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'METRO'), (SELECT id FROM product WHERE name = 'Пиво светлое'), 98);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Макароны'), 116);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ozon Fresh'), (SELECT id FROM product WHERE name = 'Йогурт клубничный'), 161);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ашан'), (SELECT id FROM product WHERE name = 'Газированный напиток'), 193);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Гречневая крупа'), 74);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Ашан'), (SELECT id FROM product WHERE name = 'Помидоры'), 155);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Перекресток'), (SELECT id FROM product WHERE name = 'Йогурт клубничный'), 199);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Зубная паста'), 113);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Стиральный порошок'), 23);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Лента'), (SELECT id FROM product WHERE name = 'Масло сливочное'), 135);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Пятерочка'), (SELECT id FROM product WHERE name = 'Курица охлажденная'), 87);
INSERT OR IGNORE INTO warehouse (shop_id, product_id, quantity) VALUES ((SELECT id FROM shop WHERE name = 'Магнит'), (SELECT id FROM product WHERE name = 'Мука пшеничная'), 119);

-- INSERTS FOR worker
CREATE TABLE worker (
worker_id INTEGER PRIMARY KEY,
shop_id INTEGER REFERENCES product (id),
name VARCHAR(255),
salary INTEGER NOT NULL,
position VARCHAR(255));

INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (1, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_1', 66596, 'Мерчендайзер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (2, (SELECT id FROM shop WHERE name = 'Магнит'), 'Сотрудник_2', 106823, 'Резчик-упаковщик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (3, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_3', 94976, 'Бухгалтер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (4, (SELECT id FROM shop WHERE name = 'Перекресток'), 'Сотрудник_4', 93061, 'Кассир');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (5, (SELECT id FROM shop WHERE name = 'Перекресток'), 'Сотрудник_5', 46792, 'Администратор');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (6, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_6', 104306, 'Уборщик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (7, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_7', 97770, 'Уборщик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (8, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_8', 49755, 'Менеджер по продажам');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (9, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_9', 40738, 'Продавец-консультант');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (10, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_10', 105178, 'Кассир');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (11, (SELECT id FROM shop WHERE name = 'Перекресток'), 'Сотрудник_11', 81126, 'Кондитер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (12, (SELECT id FROM shop WHERE name = 'Перекресток'), 'Сотрудник_12', 69630, 'Специалист по приему товара');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (13, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_13', 37937, 'Специалист по персоналу');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (14, (SELECT id FROM shop WHERE name = 'METRO'), 'Сотрудник_14', 109753, 'Резчик-упаковщик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (15, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_15', 47041, 'Товаровед');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (16, (SELECT id FROM shop WHERE name = 'Яндекс Лавка'), 'Сотрудник_16', 52349, 'Юрисконсульт');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (17, (SELECT id FROM shop WHERE name = 'Магнит'), 'Сотрудник_17', 84439, 'Менеджер по аренде');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (18, (SELECT id FROM shop WHERE name = 'Ашан'), 'Сотрудник_18', 53879, 'Охранник');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (19, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_19', 96279, 'Управляющий магазином');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (20, (SELECT id FROM shop WHERE name = 'Яндекс Лавка'), 'Сотрудник_20', 119031, 'Менеджер по продажам');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (21, (SELECT id FROM shop WHERE name = 'Ozon Fresh'), 'Сотрудник_21', 62192, 'Логист');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (22, (SELECT id FROM shop WHERE name = 'Ozon Fresh'), 'Сотрудник_22', 52724, 'Менеджер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (23, (SELECT id FROM shop WHERE name = 'Магнит'), 'Сотрудник_23', 75808, 'Грузчик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (24, (SELECT id FROM shop WHERE name = 'Магнит'), 'Сотрудник_24', 87227, 'Охранник');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (25, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_25', 33114, 'Товаровед');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (26, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_26', 83688, 'Логист');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (27, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_27', 58637, 'Администратор');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (28, (SELECT id FROM shop WHERE name = 'Ашан'), 'Сотрудник_28', 74422, 'Кладовщик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (29, (SELECT id FROM shop WHERE name = 'Перекресток'), 'Сотрудник_29', 73410, 'Мерчендайзер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (30, (SELECT id FROM shop WHERE name = 'METRO'), 'Сотрудник_30', 89409, 'Менеджер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (31, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_31', 77422, 'Контролер безопасности');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (32, (SELECT id FROM shop WHERE name = 'Яндекс Лавка'), 'Сотрудник_32', 38655, 'Бухгалтер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (33, (SELECT id FROM shop WHERE name = 'METRO'), 'Сотрудник_33', 57579, 'Товаровед');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (34, (SELECT id FROM shop WHERE name = 'ВкусВилл'), 'Сотрудник_34', 99583, 'Грузчик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (35, (SELECT id FROM shop WHERE name = 'METRO'), 'Сотрудник_35', 43950, 'Логист');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (36, (SELECT id FROM shop WHERE name = 'Ашан'), 'Сотрудник_36', 87204, 'Маркетолог');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (37, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_37', 90648, 'Системный администратор');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (38, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_38', 45039, 'Грузчик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (39, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_39', 68539, 'Товаровед');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (40, (SELECT id FROM shop WHERE name = 'ВкусВилл'), 'Сотрудник_40', 83663, 'Специалист по персоналу');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (41, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_41', 97785, 'Заведующий сменой');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (42, (SELECT id FROM shop WHERE name = 'Магнит'), 'Сотрудник_42', 90525, 'Кондитер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (43, (SELECT id FROM shop WHERE name = 'Ozon Fresh'), 'Сотрудник_43', 58361, 'Бариста');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (44, (SELECT id FROM shop WHERE name = 'ВкусВилл'), 'Сотрудник_44', 68060, 'Бариста');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (45, (SELECT id FROM shop WHERE name = 'ВкусВилл'), 'Сотрудник_45', 109552, 'Специалист по закупкам');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (46, (SELECT id FROM shop WHERE name = 'Магнит'), 'Сотрудник_46', 109022, 'Кладовщик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (47, (SELECT id FROM shop WHERE name = 'Перекресток'), 'Сотрудник_47', 78733, 'Кондитер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (48, (SELECT id FROM shop WHERE name = 'Ozon Fresh'), 'Сотрудник_48', 94859, 'Уборщик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (49, (SELECT id FROM shop WHERE name = 'Ашан'), 'Сотрудник_49', 45791, 'Продавец-консультант');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (50, (SELECT id FROM shop WHERE name = 'Перекресток'), 'Сотрудник_50', 97675, 'Контролер безопасности');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (51, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_51', 48131, 'Заместитель управляющего');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (52, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_52', 99542, 'Контролер безопасности');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (53, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_53', 45605, 'Контролер безопасности');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (54, (SELECT id FROM shop WHERE name = 'Ашан'), 'Сотрудник_54', 74987, 'Специалист по приему товара');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (55, (SELECT id FROM shop WHERE name = 'ВкусВилл'), 'Сотрудник_55', 67881, 'Продавец-консультант');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (56, (SELECT id FROM shop WHERE name = 'Ашан'), 'Сотрудник_56', 104055, 'Грузчик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (57, (SELECT id FROM shop WHERE name = 'Яндекс Лавка'), 'Сотрудник_57', 104331, 'Бариста');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (58, (SELECT id FROM shop WHERE name = 'Яндекс Лавка'), 'Сотрудник_58', 104001, 'Кондитер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (59, (SELECT id FROM shop WHERE name = 'METRO'), 'Сотрудник_59', 45010, 'Мерчендайзер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (60, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_60', 117025, 'Специалист по персоналу');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (61, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_61', 71916, 'Грузчик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (62, (SELECT id FROM shop WHERE name = 'Магнит'), 'Сотрудник_62', 55438, 'Менеджер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (63, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_63', 114226, 'Кондитер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (64, (SELECT id FROM shop WHERE name = 'ВкусВилл'), 'Сотрудник_64', 81392, 'Мерчендайзер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (65, (SELECT id FROM shop WHERE name = 'Магнит'), 'Сотрудник_65', 93996, 'Заместитель управляющего');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (66, (SELECT id FROM shop WHERE name = 'Яндекс Лавка'), 'Сотрудник_66', 74581, 'Грузчик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (67, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_67', 115402, 'Менеджер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (68, (SELECT id FROM shop WHERE name = 'Ашан'), 'Сотрудник_68', 112056, 'Контролер безопасности');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (69, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_69', 53920, 'Заведующий сменой');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (70, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_70', 52438, 'Менеджер по продажам');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (71, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_71', 111296, 'Кассир');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (72, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_72', 105245, 'Менеджер по аренде');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (73, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_73', 113817, 'Специалист по закупкам');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (74, (SELECT id FROM shop WHERE name = 'Перекресток'), 'Сотрудник_74', 79220, 'Продавец-консультант');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (75, (SELECT id FROM shop WHERE name = 'Ozon Fresh'), 'Сотрудник_75', 83705, 'Менеджер по продажам');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (76, (SELECT id FROM shop WHERE name = 'Яндекс Лавка'), 'Сотрудник_76', 88879, 'Контролер безопасности');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (77, (SELECT id FROM shop WHERE name = 'METRO'), 'Сотрудник_77', 62933, 'Охранник');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (78, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_78', 107809, 'Грузчик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (79, (SELECT id FROM shop WHERE name = 'Ozon Fresh'), 'Сотрудник_79', 46297, 'Товаровед');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (80, (SELECT id FROM shop WHERE name = 'Яндекс Лавка'), 'Сотрудник_80', 44698, 'Бариста');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (81, (SELECT id FROM shop WHERE name = 'ВкусВилл'), 'Сотрудник_81', 104385, 'Специалист по приему товара');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (82, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_82', 74318, 'Кондитер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (83, (SELECT id FROM shop WHERE name = 'Ozon Fresh'), 'Сотрудник_83', 94032, 'Специалист по приему товара');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (84, (SELECT id FROM shop WHERE name = 'ВкусВилл'), 'Сотрудник_84', 41889, 'Юрисконсульт');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (85, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_85', 49867, 'Бухгалтер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (86, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_86', 51484, 'Кассир');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (87, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_87', 89177, 'Резчик-упаковщик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (88, (SELECT id FROM shop WHERE name = 'Пятерочка'), 'Сотрудник_88', 79829, 'Логист');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (89, (SELECT id FROM shop WHERE name = 'Лента'), 'Сотрудник_89', 57721, 'Старший кассир');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (90, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_90', 30369, 'Пекарь');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (91, (SELECT id FROM shop WHERE name = 'Магнит'), 'Сотрудник_91', 117682, 'Заведующий сменой');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (92, (SELECT id FROM shop WHERE name = 'Ozon Fresh'), 'Сотрудник_92', 116239, 'Менеджер');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (93, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_93', 59440, 'Системный администратор');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (94, (SELECT id FROM shop WHERE name = 'Ozon Fresh'), 'Сотрудник_94', 87732, 'Менеджер по аренде');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (95, (SELECT id FROM shop WHERE name = 'METRO'), 'Сотрудник_95', 62897, 'Продавец-консультант');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (96, (SELECT id FROM shop WHERE name = 'Ашан'), 'Сотрудник_96', 110781, 'Юрисконсульт');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (97, (SELECT id FROM shop WHERE name = 'ВкусВилл'), 'Сотрудник_97', 72630, 'Грузчик');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (98, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_98', 31909, 'Системный администратор');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (99, (SELECT id FROM shop WHERE name = 'Дикси'), 'Сотрудник_99', 107778, 'Специалист по персоналу');
INSERT INTO worker (worker_id, shop_id, name, salary, position) VALUES (100, (SELECT id FROM shop WHERE name = 'Яндекс Лавка'), 'Сотрудник_100', 76675, 'Старший кассир');